project:
  type: book
  output-dir: docs


book:
  title: "Stats 141. Introduction to Statistics for Biology"
  chapters:
    - index.qmd
    - part: "Lectures"
      chapters: 
        - intro.qmd
        - samples.qmd
    - part: "Activities"
      chapters:
        - Week1A.qmd
        - Week1B.qmd
    - summary.qmd
#    - references.qmd
   

bibliography: references.bib
execute:
  message: false
format:
  html:
    embed-resources: false
    theme:
      - cosmo
      - brand
  pdf:
    documentclass: scrreprt
  epub: 
    cover-image: stats4bio.png

editor: visual

