project:
  type: book
  output-dir: docs


book:
  title: "Stats 141. Introduction to Statistics for Biology"
  chapters:
    - index.qmd
    - schedule.qmd
    - part: "Lectures"
      chapters: 
        - intro.qmd
        - samples.qmd
        - lec3.qmd
        - lec4.qmd
        - lec5.qmd
        - lec6.qmd
        - generative2.qmd
        - lec8.qmd
        - lec9.qmd
        - lec10.qmd
        - lec11.qmd
        - lec12.qmd
    - part: "Activities"
      chapters:
        - Week1A.qmd
        - Week1B.qmd
        - Week2A.qmd
        - Week2B.qmd
        - Week2C.qmd
        - Week3A.qmd
        - Week3B.qmd
        - Week4A.qmd
        - Week5A.qmd
        - Week5B.qmd
    - summary.qmd
    - part: "Sections"
      chapters: 
        - Week1_section.qmd
        - Week2_section.qmd
        - Week3_section.qmd
        - Week4_section.qmd
    - part: "Quizzes"
      chapters:
        - quiz1.qmd
        - quiz2.qmd
        - quiz3.qmd
        - quiz4.qmd
#    - references.qmd
   

bibliography: references.bib
execute:
  message: false
format:
  html:
    embed-resources: false
    theme:
      - cosmo
      - brand
#  pdf:
#    documentclass: scrreprt
  epub: 
    cover-image: stats4bio.png

editor: visual

