<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.36">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Linear regression and correlation</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="Lec17_files/libs/clipboard/clipboard.min.js"></script>
<script src="Lec17_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="Lec17_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="Lec17_files/libs/quarto-html/popper.min.js"></script>
<script src="Lec17_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="Lec17_files/libs/quarto-html/anchor.min.js"></script>
<link href="Lec17_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="Lec17_files/libs/quarto-html/quarto-syntax-highlighting-845c23b38eaddc0f92fda52bfe77a8c8.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="Lec17_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="Lec17_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="Lec17_files/libs/bootstrap/bootstrap-138a6193a3bd40baf1e627da441a4734.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="fullcontent quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Linear regression and correlation</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="./Figures/cat_regression.png" class="img-fluid figure-img" style="width:60.0%"></p>
<figcaption>Gemini figure (use with caution - notice where the small cat is positioned)</figcaption>
</figure>
</div>
<p>Consider a simple example in which you have measurements of body weight and heart weight for a sample of cats.</p>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Example: cat’s body weight and heart weight
</div>
</div>
<div class="callout-body-container callout-body">
<p>Assume we are interested to know whether a cat’s body weight and heart weight are associated, specifically, whether bigger cats tend to have bigger hearts.</p>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(MASS)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(patchwork)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot 1: Simple scatter plot</span></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>p1 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(cats, <span class="fu">aes</span>(<span class="at">x =</span> Bwt, <span class="at">y =</span> Hwt)) <span class="sc">+</span></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">color =</span> <span class="st">"red"</span>, <span class="at">alpha =</span> <span class="fl">0.6</span>) <span class="sc">+</span></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Body weight (kg)"</span>,</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Heart weight (g)"</span>,</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>       <span class="at">title =</span> <span class="st">"Cat's body weight vs. Heart weight"</span>) <span class="sc">+</span></span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a>p1 </span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Lec17_files/figure-html/unnamed-chunk-1-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The scatterplot suggests a general linear trend. In fact, we see a <strong>positive association</strong> between body weight and heart weight, indicating that the heavier the body, the heavier the heart. Then it is natural to try to describe the strength of the linear association. One way to measure such strength of linear association is with the <strong>correlation coefficient</strong> defined as follows:</p>
<p><span class="math display">\[
r=\frac{1}{n-1}\sum^{n}_{i=1}\left(\frac{x_{i}-\bar{x}}{s_{x}} \right)\left(\frac{y_{i}-\bar{y}}{s_{y}} \right)
\]</span> The correlation coefficient is unit free and always between -1 and 1. The sign of the correlation indicates the sign of the relationship. In our example</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cor</span>(cats<span class="sc">$</span>Bwt,cats<span class="sc">$</span>Hwt)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.8041274</code></pre>
</div>
</div>
<p>which confirms the positive <strong>linear</strong> association.</p>
<p>Things to remember:</p>
<ul>
<li><p>Our correlation is based on a sample, therefore we obtain a sample correlation and it is an estimate of the population correlation (often denoted by <span class="math inline">\(\rho\)</span> (Greek letter rho).</p></li>
<li><p>Any observed association between two variables does not imply causal connection between them.</p></li>
</ul>
<p>Given that in our example we observe a clear linear relationship between body weight and heart weight, we can superimpose a line on the plot. This is called the <strong>least-squares line</strong> or <strong>fitted regression line</strong> of <span class="math inline">\(Y\)</span> on <span class="math inline">\(X\)</span>.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Lec17_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>We will now learn how to find and interpret the line that best summarizes their linear relationship.</p>
<section id="linear-regression" class="level2">
<h2 class="anchored" data-anchor-id="linear-regression">Linear Regression</h2>
<p>Linear regression is a machine learning and statistical method that has been widely used for a long time to predict quantitative continuous responses. Although relatively simple, it is a very important model for understanding more complex machine learning models, which can be seen as generalizations of it.</p>
<p>Formally, suppose we want to understand how one or more variables — called predictors — relate to an outcome of interest — called the response variable. In our example, body weight (<span class="math inline">\(X\)</span>) is the predictor and heart weight (<span class="math inline">\(Y\)</span>) is the response. A few key questions naturally emerge:</p>
<ul>
<li>Is there a relationship between body weight and heart weight?</li>
<li>How strong is that relationship?</li>
<li>How large is the effect — for each additional kilogram of body weight, how many grams does the heart weight increase?</li>
<li>How accurately can we predict heart weight from body weight?</li>
<li>Is the relationship linear, or does it follow a more complex pattern?</li>
<li>When multiple predictors are available — such as body weight, sex, and age — which ones are truly associated with heart weight, and is there any interaction among them?</li>
</ul>
<p>Linear regression allows us to address all of these questions in a rigorous and interpretable way. And while our example is biological, the same framework applies broadly — from medicine and ecology to economics and engineering.</p>
</section>
<section id="simple-linear-regression" class="level2">
<h2 class="anchored" data-anchor-id="simple-linear-regression">Simple Linear Regression</h2>
<p>Simple linear regression refers to the most basic model when there is only one predictor, <span class="math inline">\(X\)</span>, and how that predictor is linearly related to a specific outcome, <span class="math inline">\(Y\)</span>. Mathematically, this linear relationship is <strong>modeled</strong> as follows:</p>
<p><span id="eq-1"><span class="math display">\[Y\approx \beta_{0} + \beta_{1}X. \tag{1}\]</span></span></p>
<p><a href="#eq-1" class="quarto-xref">Equation&nbsp;1</a> is interpreted as we are regressing <span class="math inline">\(Y\)</span> on <span class="math inline">\(X\)</span>, and <span class="math inline">\(\beta_{0}\)</span>, and <span class="math inline">\(\beta_{1}\)</span> are model <em>coefficients</em> or <em>parameters</em> of the model.</p>
<ul>
<li><p><span class="math inline">\(\beta_{0}\)</span> represent the <em>intercept</em></p></li>
<li><p><span class="math inline">\(\beta_{1}\)</span> the <em>slope</em> in the linear model.</p></li>
</ul>
<p>The main objective of linear regression is to use training data (in the previous example, <span class="math inline">\(X\)</span> represents measures of body weight for the sample of cats, and <span class="math inline">\(Y\)</span> observations of heart weight), to produce estimates <span class="math inline">\(\hat{\beta}_{0}\)</span> and <span class="math inline">\(\hat{\beta}_{1}\)</span> for the model coefficients that better approximate the relationship between the predictor and outcome. That is:</p>
<p><span id="eq-2"><span class="math display">\[\hat{y} = \hat{\beta}_{0} + \hat{\beta}_{1}X. \tag{2}\]</span></span></p>
<p><a href="#eq-2" class="quarto-xref">Equation&nbsp;2</a> <span class="math inline">\(\hat{y}\)</span> indicates a prediction of Y (body weight) on the basis of X(=x, heart weight), and the symbol <em>^</em> denotes a predicted value.</p>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Example: Cat’s Heart Weight</strong><br>
Linear regression of cat’s heart weight on body weight, using the dataset <span class="math inline">\(cats\)</span> from the MASS library in R.</p>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>model1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(Hwt <span class="sc">~</span> Bwt, <span class="at">data =</span> cats)</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>model1</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Hwt ~ Bwt, data = cats)

Coefficients:
(Intercept)          Bwt  
    -0.3567       4.0341  </code></pre>
</div>
</div>
<p>Notice that the intercept is equal to <span class="math inline">\(-0.3567\)</span>, which we can ignore as it is negative and has no biological meaning (heart weight when body weight = 0). The slope is important in this model, because indicates that for every 1 kg increase in body weight, heart weight increases by about 4 grams.</p>
<p><em>In summary, body weight is a strong positive predictor of heart weight in cats. Larger cats tend to have proportionally heavier hearts.</em></p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model1)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Hwt ~ Bwt, data = cats)

Residuals:
    Min      1Q  Median      3Q     Max 
-3.5694 -0.9634 -0.0921  1.0426  5.1238 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  -0.3567     0.6923  -0.515    0.607    
Bwt           4.0341     0.2503  16.119   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 1.452 on 142 degrees of freedom
Multiple R-squared:  0.6466,    Adjusted R-squared:  0.6441 
F-statistic: 259.8 on 1 and 142 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p><strong>Goodness of fit:</strong><br>
<em>R-squared = 0.64</em> - indicates that body weight explains 64% of the total variation in heart weight.<br>
</p>
<p><em>p-value &lt; 2.2e-16</em> - indicates that the relationship is statistically significant.<br>
</p>
<p><em>Residual standard Error: 1.452g</em> - indicates how far off predictions typically are (we are typically wrong by about 1.42 grams)</p>
<section id="estimating-the-coefficients" class="level3">
<h3 class="anchored" data-anchor-id="estimating-the-coefficients">Estimating the coefficients</h3>
<p>The coefficients <span class="math inline">\(\beta_{0}\)</span> and <span class="math inline">\(\beta_{1}\)</span> in the linear model are unknown. The goal is therefore to obtain estimates <span class="math inline">\(\hat{\beta}_{0}\)</span> and <span class="math inline">\(\hat{\beta}_{1}\)</span> such that the linear model <a href="#eq-1" class="quarto-xref">Equation&nbsp;1</a> fits the <span class="math inline">\(n = 144\)</span> data points as closely as possible.</p>
<p>There are several ways to measure <em>closeness</em>, however the most common approach involves minimizing the <em>least squares</em> criterion.</p>
<p>In least squares, we calculate the difference between the observed value <span class="math inline">\(y_{i}\)</span> and the predicted value <span class="math inline">\(\hat{y}_{i}\)</span> obtained from the fitted model (from <a href="#eq-2" class="quarto-xref">Equation&nbsp;2</a> above: <span class="math inline">\(\hat{y}_{i} = \hat{\beta}_{0} + \hat{\beta}_{1}x_{i}\)</span>). That is, <span class="math inline">\(e_{i} = y_{i} - \hat{y}_{i}\)</span> represents the <em>i-th residual</em> for observation <span class="math inline">\(i\)</span>. We illustrate these residuals for the <span class="math inline">\(cats\)</span> sample in the plot below, shown as vertical lines from each observed data point (in red) to the fitted line.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Lec17_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Then, we define the <em>residual sum of squares</em> (RSS) as:</p>
<p><span id="eq-3"><span class="math display">\[RSS = e^{2}_{1} + e^{2}_{2} + \dots + e^{2}_{n} \tag{3}\]</span></span></p>
<p>The <em>least squares coefficient estimates</em> <span class="math inline">\(\hat{\beta}_{0}\)</span> and <span class="math inline">\(\hat{\beta}_{1}\)</span> for simple linear regression are obtained by minimizing the RSS, which after some calculus yields:</p>
<p><span id="eq-4"><span class="math display">\[\begin{align}
\hat{\beta}_{1} &amp;= \frac{\sum_{i=1}^{n}(x_{i}-\bar{x})(y_{i}-\bar{y})}{\sum_{i=1}^{n}(x_{i}-\bar{x})^2}=r \left(\frac{s_{y}}{s_{x}} \right), \\
\hat{\beta}_{0} &amp;= \bar{y} - \hat{\beta}_{1}\bar{x},
\end{align} \tag{4}\]</span></span></p>
<p>where <span class="math inline">\(\bar{y}\equiv \frac{1}{n}\sum_{i=1}^{n}y_{i}\)</span> and <span class="math inline">\(\bar{x}\equiv \frac{1}{n}\sum_{i=1}^{n}x_{i}\)</span> are the sample means.</p>
</section>
<section id="assessing-the-accuracy-of-the-coefficient-estimates" class="level3">
<h3 class="anchored" data-anchor-id="assessing-the-accuracy-of-the-coefficient-estimates">Assessing the accuracy of the coefficient estimates</h3>
<p>A natural question about the linear regression model is how accurate the coefficient estimates are — that is, how far <span class="math inline">\(\hat{\beta}_{0}\)</span> and <span class="math inline">\(\hat{\beta}_{1}\)</span> are from the true values <span class="math inline">\(\beta_{0}\)</span> and <span class="math inline">\(\beta_{1}\)</span>. To answer this question, we compute the <em>standard errors</em> associated with <span class="math inline">\(\hat{\beta}_{0}\)</span> and <span class="math inline">\(\hat{\beta}_{1}\)</span> using the following formulas:</p>
<p><span id="eq-5"><span class="math display">\[SE(\hat{\beta}_{0})^{2}=\sigma^{2}\left[\frac{1}{n}+\frac{\bar{x}^{2}}{\sum_{i=1}^{n}(x_{i}-\bar{x})^{2}}\right], \quad SE(\hat{\beta}_{1})^{2}=\frac{\sigma^{2}}{\sum_{i=1}^{n}(x_{i}-\bar{x})^{2}} \tag{5}\]</span></span></p>
<p>where <span class="math inline">\(\sigma^{2}=Var(\epsilon)\)</span> is the variance of the error terms, which is unknown but can be estimated empirically via the RSE defined as follows:</p>
<p><span class="math display">\[
RSE=\sqrt{\frac{RSS}{n-2}}
\]</span></p>
<p>Strictly, these equations are valid only when the errors <span class="math inline">\(\epsilon_{i}\)</span> for each observation have constant variance <span class="math inline">\(\sigma^{2}\)</span> and are uncorrelated, but in practice they provide a good approximation.</p>
<p>Notice that unlike <span class="math inline">\(e_{i}\)</span>, which are the observed residuals obtained from the fitted model, <span class="math inline">\(\epsilon_{i}\)</span> are the underlying population errors that arise when approximating the relationship between <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span> through a linear model, and are therefore unobserved.</p>
<p>Once we obtain the standard errors of the estimates, we can construct <em>confidence intervals</em>. A 95% confidence interval is defined as a range of values such that, with 95% probability, the range will contain the true unknown value of the parameter. Confidence intervals are constructed from the data and have the property that if we take repeated samples and construct a confidence interval for each sample, 95% of those intervals will contain the true unknown value of the parameter. For the linear regression model, the 95% confidence intervals for <span class="math inline">\(\beta_{0}\)</span> and <span class="math inline">\(\beta_{1}\)</span> are approximated as:</p>
<p><span id="eq-6"><span class="math display">\[\left[\hat{\beta}_{0}-2\cdot SE(\hat{\beta}_{0}),\ \hat{\beta}_{0}+2\cdot SE(\hat{\beta}_{0})\right] \tag{6}\]</span></span> <span id="eq-7"><span class="math display">\[\left[\hat{\beta}_{1}-2\cdot SE(\hat{\beta}_{1}),\ \hat{\beta}_{1}+2\cdot SE(\hat{\beta}_{1})\right] \tag{7}\]</span></span></p>
<p>In the previous example, the standard errors for the intercept and slope were 0.6923 and 0.2503, respectively. The associated confidence intervals are therefore:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">confint</span>(model1)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>                2.5 %   97.5 %
(Intercept) -1.725163 1.011838
Bwt          3.539343 4.528782</code></pre>
</div>
</div>
<p>We are thus 95% confident that for every 1 kg increase in body weight, the true average increase in heart weight is between 3.54 and 4.53 grams.</p>
<p>Standard errors are also useful for testing the most common hypothesis in regression — that there is no relationship between <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span> (i.e., that a cat’s body weight is not associated with its heart weight). Formally, the <em>null hypothesis</em> states that there is no relationship between <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span>, versus the <em>alternative hypothesis</em> that there is some relationship between <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span>. Mathematically, this corresponds to testing:</p>
<p><span id="eq-8"><span class="math display">\[\begin{align}
H_{0} &amp;: \beta_{1} = 0 \\
&amp;\text{versus} \\
H_{a} &amp;: \beta_{1} \neq 0
\end{align} \tag{8}\]</span></span></p>
<p>To test the null hypothesis, we need to determine how far <span class="math inline">\(\hat{\beta}_{1}\)</span> is from zero to be confident that <span class="math inline">\(\beta_{1}\)</span> is nonzero. This depends on the accuracy of the estimate, given by <span class="math inline">\(SE(\hat{\beta}_{1})\)</span>. The smaller <span class="math inline">\(SE(\hat{\beta}_{1})\)</span> is, the more likely that <span class="math inline">\(\beta_{1}\)</span> differs from zero; conversely, the larger the standard error, the larger <span class="math inline">\(\hat{\beta}_{1}\)</span> needs to be in order to reject the null hypothesis. In practice, we rely on a <em>t-statistic</em>, given by</p>
<p><span id="eq-9"><span class="math display">\[t=\frac{\hat{\beta}_{1}-0}{SE(\hat{\beta}_{1})}, \tag{9}\]</span></span></p>
<p>which measures how many standard deviations <span class="math inline">\(\hat{\beta}_{1}\)</span> is from zero. If there is no relationship between <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span>, we expect <span class="math inline">\(t\)</span> to follow a <span class="math inline">\(t\)</span>-distribution with <span class="math inline">\(n-2\)</span> degrees of freedom. The larger the observed value of <span class="math inline">\(t\)</span> relative to the theoretical <span class="math inline">\(t\)</span>-distribution, the lower the probability that <span class="math inline">\(\beta_{1} = 0\)</span>. This probability is called the <em>p-value</em>, which in our example was practically zero (<span class="math inline">\(&lt;2\times10^{-16}\)</span>), providing strong evidence that <span class="math inline">\(\hat{\beta}_{1} \neq 0\)</span>, or equivalently that it is <em>statistically significant</em>. A small <em>p-value</em> indicates that it is unlikely to observe such a substantial association between the predictor and the response by chance alone. We therefore reject the null hypothesis when the <em>p-value</em> is sufficiently small — typically below 0.05 or 0.01.</p>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>