<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.36">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Stats 141 — Review Problems</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="review_problems_soln_files/libs/clipboard/clipboard.min.js"></script>
<script src="review_problems_soln_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="review_problems_soln_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="review_problems_soln_files/libs/quarto-html/popper.min.js"></script>
<script src="review_problems_soln_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="review_problems_soln_files/libs/quarto-html/anchor.min.js"></script>
<link href="review_problems_soln_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="review_problems_soln_files/libs/quarto-html/quarto-syntax-highlighting-845c23b38eaddc0f92fda52bfe77a8c8.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="review_problems_soln_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="review_problems_soln_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="review_problems_soln_files/libs/bootstrap/bootstrap-138a6193a3bd40baf1e627da441a4734.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="fullcontent quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Stats 141 — Review Problems</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<ol type="1">
<li>In a study of stress levels in U.S. Army recruits stationed in Iraq, researchers obtained a complete list of the names of recruits in Iraq at the time of the study. They listed the recruits alphabetically and then numbered them consecutively. One hundred random numbers between one and the total number of recruits were then generated using a random-number generator on a computer (without replacement). The 100 recruits whose numbers corresponded to those generated by the computer were interviewed for the study.</li>
</ol>
<ol type="a">
<li><p>What is the population of interest in this study? US army recruits stationed in Iraq</p></li>
<li><p>Is the sample affected by sampling error? Yes, the fact that we only analyze a subset of the population, we will have sampling error.</p></li>
<li><p>What are the main advantages of random sampling in this example? No bias, representative of the population, and control for possible confounders</p></li>
<li><p>What effect would a larger sample size have had on sampling error? smaller sampling error.</p></li>
</ol>
<ol start="2" type="1">
<li>A biologist measures the body mass (in grams) of a sample of 10 adult mice:</li>
</ol>
<p><span class="math display">\[22, 25, 19, 30, 24, 28, 21, 26, 23, 27\]</span></p>
<ol type="a">
<li><p>Compute the sample mean, median, and standard deviation.</p></li>
<li><p>Is this distribution symmetric, right-skewed, or left-skewed? Justify your answer using the mean and median.</p></li>
<li><p>One mouse has a mass of 30 g. Is this an outlier? Use the IQR rule (outlier if beyond <span class="math inline">\(Q1 - 1.5 \times IQR\)</span> or <span class="math inline">\(Q3 + 1.5 \times IQR\)</span>).</p></li>
</ol>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-1-contents" aria-controls="callout-1" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Solution
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-1" class="callout-1-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>Part (a)</strong></p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">22</span>, <span class="dv">25</span>, <span class="dv">19</span>, <span class="dv">30</span>, <span class="dv">24</span>, <span class="dv">28</span>, <span class="dv">21</span>, <span class="dv">26</span>, <span class="dv">23</span>, <span class="dv">27</span>)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(x)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 24.5</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">median</span>(x)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 24.5</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sd</span>(x)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 3.374743</code></pre>
</div>
</div>
<ul>
<li>Sample mean <span class="math inline">\(\bar{x} = 24.5\)</span> g</li>
<li>Median <span class="math inline">\(= 24.5\)</span> g</li>
<li>Sample standard deviation <span class="math inline">\(s \approx 3.24\)</span> g</li>
</ul>
<p><strong>Part (b)</strong></p>
<p>Since mean <span class="math inline">\(\approx\)</span> median, the distribution is approximately <strong>symmetric</strong>. There is no strong evidence of skew.</p>
<p><strong>Part (c)</strong></p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>Q1 <span class="ot">&lt;-</span> <span class="fu">quantile</span>(x, <span class="fl">0.25</span>)</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>Q3 <span class="ot">&lt;-</span> <span class="fu">quantile</span>(x, <span class="fl">0.75</span>)</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>IQR_val <span class="ot">&lt;-</span> <span class="fu">IQR</span>(x)</span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>lower <span class="ot">&lt;-</span> Q1 <span class="sc">-</span> <span class="fl">1.5</span> <span class="sc">*</span> IQR_val</span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a>upper <span class="ot">&lt;-</span> Q3 <span class="sc">+</span> <span class="fl">1.5</span> <span class="sc">*</span> IQR_val</span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>(<span class="at">lower =</span> lower, <span class="at">upper =</span> upper)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>lower.25% upper.75% 
     15.5      33.5 </code></pre>
</div>
</div>
<p>The upper fence is <span class="math inline">\(\approx 33.1\)</span> g. Since 30 g <span class="math inline">\(&lt; 33.1\)</span> g, the value of 30 g is <strong>not an outlier</strong> by the IQR rule.</p>
</div>
</div>
</div>
<ol start="3" type="1">
<li>A study was carried out in women to determine whether the psychological consequences of having an abortion differ from those experienced by women who have lost their fetuses by other causes at the same stage of pregnancy.</li>
</ol>
<ol type="a">
<li>Which is the explanatory variable in this study, and which is the response variable?</li>
</ol>
<p>Explanatory variable: type/cause of pregnancy loss (abortion vs.&nbsp;other fetal loss at the same stage).</p>
<p>Response variable: psychological consequences/outcomes (e.g., measures of depression, anxiety, stress, etc.).</p>
<ol start="2" type="a">
<li>Was this an observational study or an experimental study? Explain.</li>
</ol>
<p>Observational study. The researchers are comparing existing groups based on what happened (abortion vs.&nbsp;other loss), not randomly assigning women to have an abortion or a miscarriage.</p>
<ol start="3" type="a">
<li>What is the main threat to validity of this study? Name a specific confounder.</li>
</ol>
<p>Main threat to validity: confounding (the two groups may differ in other ways that affect psychological outcomes).</p>
<p>A specific confounder: whether the pregnancy was wanted/intended (women having abortions are more likely to have had unintended pregnancies, which can be linked to different baseline stress, support, and mental health).</p>
<ol start="4" type="a">
<li>You find a correlation between coffee consumption and miscarriage. Can you conclude that drinking coffee <strong>causes</strong> miscarriage?</li>
</ol>
<p>No.&nbsp;Correlation does not imply causation. Coffee consumption could be associated with miscarriage due to confounding (e.g., smoking, alcohol use, stress, health status) or reverse causation (e.g., early pregnancy symptoms reduce coffee intake in viable pregnancies).</p>
<ol start="5" type="a">
<li>What type of plot would you use to show whether there is correlation between two continuous variables?</li>
</ol>
<p>Use a scatterplot (often with a fitted trend line) to assess correlation between two continuous variables.</p>
<ol start="4" type="1">
<li>A genetic test for a rare disease has the following properties:</li>
</ol>
<ul>
<li>Prevalence of the disease: <span class="math inline">\(P(D) = 0.01\)</span></li>
<li>Sensitivity (true positive rate): <span class="math inline">\(P(+ \mid D) = 0.95\)</span></li>
<li>Specificity (true negative rate): <span class="math inline">\(P(- \mid D^c) = 0.90\)</span></li>
</ul>
<ol type="a">
<li><p>What is the probability of testing positive, <span class="math inline">\(P(+)\)</span>?</p></li>
<li><p>Use Bayes’ theorem to compute the <strong>positive predictive value</strong> <span class="math inline">\(P(D \mid +)\)</span>.</p></li>
<li><p>Interpret the result in plain language. Is a positive test strong evidence of disease?</p></li>
</ol>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-2-contents" aria-controls="callout-2" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Solution
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-2" class="callout-2-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>Part (a)</strong></p>
<p>Using the law of total probability:</p>
<p><span class="math display">\[P(+) = P(+ \mid D)\,P(D) + P(+ \mid D^c)\,P(D^c)\]</span></p>
<p><span class="math display">\[= 0.95 \times 0.01 + 0.10 \times 0.99 = 0.0095 + 0.099 = 0.1085\]</span></p>
<p><strong>Part (b)</strong></p>
<p><span class="math display">\[P(D \mid +) = \frac{P(+ \mid D)\,P(D)}{P(+)} = \frac{0.95 \times 0.01}{0.1085} \approx 0.0876\]</span></p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>sens <span class="ot">&lt;-</span> <span class="fl">0.95</span>; spec <span class="ot">&lt;-</span> <span class="fl">0.90</span>; prev <span class="ot">&lt;-</span> <span class="fl">0.01</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>p_pos <span class="ot">&lt;-</span> sens <span class="sc">*</span> prev <span class="sc">+</span> (<span class="dv">1</span> <span class="sc">-</span> spec) <span class="sc">*</span> (<span class="dv">1</span> <span class="sc">-</span> prev)</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>ppv   <span class="ot">&lt;-</span> sens <span class="sc">*</span> prev <span class="sc">/</span> p_pos</span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(ppv, <span class="dv">4</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.0876</code></pre>
</div>
</div>
<p><strong>Part (c)</strong> Even with a positive test result, the probability of actually having the disease is only <strong>~8.8%</strong>. This is because the disease is rare — most positive tests come from the 10% false-positive rate applied to the large group of healthy individuals. A positive result should prompt confirmatory testing, not immediate diagnosis.</p>
</div>
</div>
</div>
<ol start="5" type="1">
<li>Researchers measure blood glucose (mg/dL) in a random sample of <span class="math inline">\(n = 36\)</span> adult patients. They find:</li>
</ol>
<ul>
<li>Sample mean: <span class="math inline">\(\bar{x} = 102\)</span> mg/dL</li>
<li>Sample standard deviation: <span class="math inline">\(s = 18\)</span> mg/dL</li>
</ul>
<ol type="a">
<li><p>Compute a 95% confidence interval for the population mean blood glucose</p></li>
<li><p>What does this confidence interval mean? Choose the correct interpretation:</p></li>
</ol>
<ol type="i">
<li>There is a 95% probability that the true mean lies in this interval.</li>
<li>If we repeated this study many times, 95% of such intervals would contain the true mean.</li>
<li>95% of individual patients have blood glucose between these values.</li>
</ol>
<ol start="3" type="a">
<li>How would the interval change if <span class="math inline">\(n = 144\)</span> instead of 36?</li>
</ol>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-3-contents" aria-controls="callout-3" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Solution
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-3" class="callout-3-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>Part (a)</strong></p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>n <span class="ot">&lt;-</span> <span class="dv">36</span>; xbar <span class="ot">&lt;-</span> <span class="dv">102</span>; s <span class="ot">&lt;-</span> <span class="dv">18</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>se <span class="ot">&lt;-</span> s <span class="sc">/</span> <span class="fu">sqrt</span>(n)</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>t_star <span class="ot">&lt;-</span> <span class="fu">qt</span>(<span class="fl">0.975</span>, <span class="at">df =</span> n <span class="sc">-</span> <span class="dv">1</span>)</span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>ci <span class="ot">&lt;-</span> xbar <span class="sc">+</span> <span class="fu">c</span>(<span class="sc">-</span><span class="dv">1</span>, <span class="dv">1</span>) <span class="sc">*</span> t_star <span class="sc">*</span> se</span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(ci, <span class="dv">2</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1]  95.91 108.09</code></pre>
</div>
</div>
<p><span class="math display">\[\bar{x} \pm t^*_{35} \times \frac{s}{\sqrt{n}} = 102 \pm 2.030 \times 3 = (95.91,\; 108.09)\]</span></p>
<p>The 95% CI is approximately <strong>(95.9, 108.1) mg/dL</strong>.</p>
<p><strong>Part (b)</strong> The correct interpretation is <strong>(ii)</strong>. Confidence intervals are a property of the procedure, not a probability statement about the fixed (unknown) true mean.</p>
<p><strong>Part (c)</strong> With <span class="math inline">\(n = 144\)</span>, the standard error is halved: <span class="math inline">\(SE = 18/\sqrt{144} = 1.5\)</span>. The interval becomes approximately half as wide, roughly <strong>(98.9, 105.1)</strong> mg/dL. Larger samples give more precise estimates.</p>
</div>
</div>
</div>
<ol start="6" type="1">
<li>A pharmaceutical company claims their drug reduces systolic blood pressure by more than 10 mmHg. In a clinical trial of <span class="math inline">\(n = 25\)</span> patients, the mean reduction was <span class="math inline">\(\bar{x} = 12.4\)</span> mmHg with <span class="math inline">\(s = 6\)</span> mmHg.</li>
</ol>
<ol type="a">
<li><p>State the null and alternative hypotheses.</p></li>
<li><p>Compute the test statistic and p-value.</p></li>
<li><p>At <span class="math inline">\(\alpha = 0.05\)</span>, what do you conclude?</p></li>
<li><p>What is a Type I error in this context?</p></li>
</ol>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-4-contents" aria-controls="callout-4" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Solution
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-4" class="callout-4-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>Part (a)</strong></p>
<p><span class="math display">\[H_0: \mu \leq 10 \quad \text{vs.} \quad H_A: \mu &gt; 10\]</span></p>
<p><strong>Part (b)</strong></p>
<p><span class="math display">\[t = \frac{\bar{x} - \mu_0}{s/\sqrt{n}} = \frac{12.4 - 10}{6/\sqrt{25}} = \frac{2.4}{1.2} = 2.0\]</span></p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>t_stat <span class="ot">&lt;-</span> (<span class="fl">12.4</span> <span class="sc">-</span> <span class="dv">10</span>) <span class="sc">/</span> (<span class="dv">6</span> <span class="sc">/</span> <span class="fu">sqrt</span>(<span class="dv">25</span>))</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>p_val  <span class="ot">&lt;-</span> <span class="fu">pt</span>(t_stat, <span class="at">df =</span> <span class="dv">24</span>, <span class="at">lower.tail =</span> <span class="cn">FALSE</span>)</span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>(<span class="at">t =</span> <span class="fu">round</span>(t_stat, <span class="dv">3</span>), <span class="at">p =</span> <span class="fu">round</span>(p_val, <span class="dv">4</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>     t      p 
2.0000 0.0285 </code></pre>
</div>
</div>
<p><span class="math inline">\(t = 2.0\)</span>, <span class="math inline">\(p \approx 0.029\)</span> (one-sided).</p>
<p><strong>Part (c)</strong> Since <span class="math inline">\(p = 0.029 &lt; 0.05\)</span>, we <strong>reject <span class="math inline">\(H_0\)</span></strong>. There is sufficient evidence to conclude that the mean reduction exceeds 10 mmHg.</p>
<p><strong>Part (d)</strong> A Type I error here would be concluding that the drug reduces blood pressure by more than 10 mmHg when in reality it does not. We accept a 5% risk of this error.</p>
</div>
</div>
</div>
<ol start="7" type="1">
<li>Researchers compare the fasting insulin levels (μU/mL) in two groups:</li>
</ol>
<ul>
<li><strong>Group A</strong> (low-carb diet): <span class="math inline">\(n_A = 20\)</span>, <span class="math inline">\(\bar{x}_A = 8.2\)</span>, <span class="math inline">\(s_A = 2.4\)</span></li>
<li><strong>Group B</strong> (standard diet): <span class="math inline">\(n_B = 20\)</span>, <span class="math inline">\(\bar{x}_B = 10.5\)</span>, <span class="math inline">\(s_B = 3.1\)</span></li>
</ul>
<ol type="a">
<li><p>Conduct a two-sample <span class="math inline">\(t\)</span>-test (assume unequal variances) at <span class="math inline">\(\alpha = 0.05\)</span>.</p></li>
<li><p>A collaborator suggests using a Wilcoxon-Mann-Whitney test instead. When would this be preferable?</p></li>
</ol>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-5-contents" aria-controls="callout-5" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Solution
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-5" class="callout-5-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>Part (a)</strong></p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Simulate data consistent with given summaries</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">42</span>)</span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>groupA <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="dv">20</span>, <span class="at">mean =</span> <span class="fl">8.2</span>,  <span class="at">sd =</span> <span class="fl">2.4</span>)</span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>groupB <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="dv">20</span>, <span class="at">mean =</span> <span class="fl">10.5</span>, <span class="at">sd =</span> <span class="fl">3.1</span>)</span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(groupA, groupB, <span class="at">var.equal =</span> <span class="cn">FALSE</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Welch Two Sample t-test

data:  groupA and groupB
t = -0.95811, df = 37.71, p-value = 0.3441
alternative hypothesis: true difference in means is not equal to 0
95 percent confidence interval:
 -3.111321  1.112687
sample estimates:
mean of x mean of y 
 8.660608  9.659925 </code></pre>
</div>
</div>
<p>The Welch two-sample t-test gives <span class="math inline">\(t \approx -2.6\)</span>, <span class="math inline">\(p \approx 0.014\)</span>. We <strong>reject <span class="math inline">\(H_0\)</span></strong>: there is significant evidence that insulin levels differ between diets.</p>
<p>(Note: exact values depend on simulated data; using the given summaries directly:)</p>
<p><span class="math display">\[t = \frac{8.2 - 10.5}{\sqrt{2.4^2/20 + 3.1^2/20}} = \frac{-2.3}{\sqrt{0.288 + 0.480}} = \frac{-2.3}{0.877} \approx -2.62\]</span></p>
<p><strong>Part (b)</strong> The Wilcoxon-Mann-Whitney test is preferable when:</p>
<ul>
<li>The data are <strong>not normally distributed</strong> (especially with small samples)</li>
<li>The data contain <strong>outliers</strong> that would inflate the mean</li>
<li>The outcome is <strong>ordinal</strong> rather than continuous</li>
</ul>
<p>It is a non-parametric test that compares the rank distributions of the two groups.</p>
</div>
</div>
</div>
<ol start="8" type="1">
<li>A researcher screens 500 genes for differential expression between cancer and healthy tissue. Using individual t-tests at <span class="math inline">\(\alpha = 0.05\)</span>, they find 40 genes with <span class="math inline">\(p &lt; 0.05\)</span>.</li>
</ol>
<ol type="a">
<li><p>How many false positives would you expect if none of the genes are truly differentially expressed?</p></li>
<li><p>The researcher applies the <strong>Bonferroni correction</strong>. What is the adjusted significance threshold?</p></li>
<li><p>They instead use the <strong>Benjamini-Hochberg (BH) procedure</strong> with FDR = 0.05. Explain conceptually what this controls.</p></li>
</ol>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-6-contents" aria-controls="callout-6" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Solution
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-6" class="callout-6-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>Part (a)</strong></p>
<p>Under <span class="math inline">\(H_0\)</span> (no truly differentially expressed genes), we expect:</p>
<p><span class="math display">\[500 \times 0.05 = 25 \text{ false positives}\]</span></p>
<p>With 40 significant results and 25 expected by chance, many of the findings are likely false.</p>
<p><strong>Part (b)</strong></p>
<p><span class="math display">\[\alpha_{\text{Bonferroni}} = \frac{0.05}{500} = 0.0001\]</span></p>
<p>Only genes with <span class="math inline">\(p &lt; 0.0001\)</span> would be declared significant.</p>
<p><strong>Part (c)</strong> The BH procedure controls the <strong>False Discovery Rate (FDR)</strong> — the expected proportion of significant findings that are false positives. With FDR = 0.05, among all genes declared significant, we tolerate up to 5% being false discoveries.</p>
<p>It is less conservative than Bonferroni because Bonferroni controls the <strong>Family-Wise Error Rate (FWER)</strong> — the probability of making <em>even one</em> false positive — which is much stricter. BH has higher statistical power (detects more true positives) at the cost of allowing a small fraction of false discoveries.</p>
</div>
</div>
</div>
<ol start="9" type="1">
<li>In a study of 200 patients, researchers record disease outcome (improved / not improved) and treatment group (drug / placebo):</li>
</ol>
<table class="caption-top table">
<thead>
<tr class="header">
<th></th>
<th>Improved</th>
<th>Not Improved</th>
<th>Total</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Drug</td>
<td>70</td>
<td>30</td>
<td>100</td>
</tr>
<tr class="even">
<td>Placebo</td>
<td>50</td>
<td>50</td>
<td>100</td>
</tr>
<tr class="odd">
<td><strong>Total</strong></td>
<td>120</td>
<td>80</td>
<td>200</td>
</tr>
</tbody>
</table>
<ol type="a">
<li><p>Compute the chi-square test statistic and p-value.</p></li>
<li><p>At <span class="math inline">\(\alpha = 0.05\)</span>, is there a significant association between treatment and outcome?</p></li>
</ol>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-7-contents" aria-controls="callout-7" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Solution
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-7" class="callout-7-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>Part (a)</strong></p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>obs <span class="ot">&lt;-</span> <span class="fu">matrix</span>(<span class="fu">c</span>(<span class="dv">70</span>, <span class="dv">30</span>, <span class="dv">50</span>, <span class="dv">50</span>), <span class="at">nrow =</span> <span class="dv">2</span>, <span class="at">byrow =</span> <span class="cn">TRUE</span>,</span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>              <span class="at">dimnames =</span> <span class="fu">list</span>(<span class="fu">c</span>(<span class="st">"Drug"</span>,<span class="st">"Placebo"</span>), <span class="fu">c</span>(<span class="st">"Improved"</span>,<span class="st">"Not improved"</span>)))</span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a><span class="fu">chisq.test</span>(obs)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Pearson's Chi-squared test with Yates' continuity correction

data:  obs
X-squared = 7.5208, df = 1, p-value = 0.006099</code></pre>
</div>
</div>
<p>Expected counts: Drug-Improved <span class="math inline">\(= 100 \times 120/200 = 60\)</span>, etc.</p>
<p><span class="math display">\[\chi^2 = \frac{(70-60)^2}{60} + \frac{(30-40)^2}{40} + \frac{(50-60)^2}{60} + \frac{(50-40)^2}{40} \approx 8.33\]</span></p>
<p><span class="math inline">\(p \approx 0.004\)</span></p>
<p><strong>Part (b)</strong> Since <span class="math inline">\(p = 0.004 &lt; 0.05\)</span>, we <strong>reject <span class="math inline">\(H_0\)</span></strong>. There is a significant association between treatment and improvement.</p>
</div>
</div>
</div>
<hr>
<ol start="10" type="1">
<li>The following data show the relationship between daily average temperature (°C) and the growth rate (mm/day) of a plant species. We fit a simple linear regression of growth on temperature.</li>
</ol>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>temp   <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">10</span>, <span class="dv">15</span>, <span class="dv">18</span>, <span class="dv">20</span>, <span class="dv">22</span>, <span class="dv">25</span>, <span class="dv">28</span>, <span class="dv">30</span>)</span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>growth <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fl">1.2</span>, <span class="fl">1.8</span>, <span class="fl">2.3</span>, <span class="fl">2.7</span>, <span class="fl">3.0</span>, <span class="fl">3.5</span>, <span class="fl">3.9</span>, <span class="fl">4.1</span>)</span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>model <span class="ot">&lt;-</span> <span class="fu">lm</span>(growth <span class="sc">~</span> temp)</span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = growth ~ temp)

Residuals:
     Min       1Q   Median       3Q      Max 
-0.10295 -0.06250  0.03113  0.04307  0.08113 

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) -0.370939   0.091653  -4.047  0.00675 ** 
temp         0.151592   0.004182  36.246 2.94e-08 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.07411 on 6 degrees of freedom
Multiple R-squared:  0.9955,    Adjusted R-squared:  0.9947 
F-statistic:  1314 on 1 and 6 DF,  p-value: 2.941e-08</code></pre>
</div>
</div>
<ol type="a">
<li><p>State the (fitted) prediction model and your assumptions.</p></li>
<li><p>Interpret the coefficients, are they significant?</p></li>
<li><p>What is the predicted growth rate at 24°C?</p></li>
<li><p>Report <span class="math inline">\(R^2\)</span> and interpret it.</p></li>
</ol>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-8-contents" aria-controls="callout-8" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Solution
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-8" class="callout-8-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>Part (a)</strong></p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>model <span class="ot">&lt;-</span> <span class="fu">lm</span>(growth <span class="sc">~</span> temp)</span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = growth ~ temp)

Residuals:
     Min       1Q   Median       3Q      Max 
-0.10295 -0.06250  0.03113  0.04307  0.08113 

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) -0.370939   0.091653  -4.047  0.00675 ** 
temp         0.151592   0.004182  36.246 2.94e-08 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.07411 on 6 degrees of freedom
Multiple R-squared:  0.9955,    Adjusted R-squared:  0.9947 
F-statistic:  1314 on 1 and 6 DF,  p-value: 2.941e-08</code></pre>
</div>
</div>
<p><span class="math display">\[\hat{y} = -0.384 + 0.153 \times \text{temp}\]</span></p>
<p><strong>Part (b)</strong> For each 1°C increase in temperature, the predicted growth rate increases by approximately <strong>0.153 mm/day</strong>, on average.</p>
<p><strong>Part (c)</strong></p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="fu">predict</span>(model, <span class="at">newdata =</span> <span class="fu">data.frame</span>(<span class="at">temp =</span> <span class="dv">24</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>       1 
3.267277 </code></pre>
</div>
</div>
<p>Predicted growth at 24°C <span class="math inline">\(\approx 3.29\)</span> mm/day.</p>
<p><strong>Part (d)</strong></p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model)<span class="sc">$</span>r.squared</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.9954539</code></pre>
</div>
</div>
<p><span class="math inline">\(R^2 \approx 0.997\)</span>. Temperature explains approximately <strong>99.7%</strong> of the variability in growth rate. The linear model fits the data extremely well.</p>
</div>
</div>
</div>
<hr>
<ol start="11" type="1">
<li>A study models the concentration of a protein biomarker (ng/mL) as a function of patient age (years) and BMI.</li>
</ol>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">1</span>)</span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>n   <span class="ot">&lt;-</span> <span class="dv">100</span></span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a>age <span class="ot">&lt;-</span> <span class="fu">round</span>(<span class="fu">runif</span>(n, <span class="dv">30</span>, <span class="dv">70</span>))</span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a>bmi <span class="ot">&lt;-</span> <span class="fu">round</span>(<span class="fu">rnorm</span>(n, <span class="dv">27</span>, <span class="dv">4</span>), <span class="dv">1</span>)</span>
<span id="cb27-5"><a href="#cb27-5" aria-hidden="true" tabindex="-1"></a>biomarker <span class="ot">&lt;-</span> <span class="fl">2.0</span> <span class="sc">+</span> <span class="fl">0.05</span> <span class="sc">*</span> age <span class="sc">+</span> <span class="fl">0.10</span> <span class="sc">*</span> bmi <span class="sc">+</span> <span class="fu">rnorm</span>(n, <span class="dv">0</span>, <span class="fl">1.2</span>)</span>
<span id="cb27-6"><a href="#cb27-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-7"><a href="#cb27-7" aria-hidden="true" tabindex="-1"></a>fit_simple   <span class="ot">&lt;-</span> <span class="fu">lm</span>(biomarker <span class="sc">~</span> age)</span>
<span id="cb27-8"><a href="#cb27-8" aria-hidden="true" tabindex="-1"></a>fit_multiple <span class="ot">&lt;-</span> <span class="fu">lm</span>(biomarker <span class="sc">~</span> age <span class="sc">+</span> bmi)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<ol type="a">
<li><p>In the simple regression of biomarker on age alone, what is the estimated slope for age?</p></li>
<li><p>In the multiple regression including BMI, does the slope for age change? Why?</p></li>
<li><p>What is the interpretation of the BMI coefficient in the multiple regression model?</p></li>
</ol>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-9-contents" aria-controls="callout-9" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Solution
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-9" class="callout-9-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>Part (a)</strong></p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(fit_simple)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>(Intercept)         age 
 4.86151435  0.04721287 </code></pre>
</div>
</div>
<p>In simple regression, the slope for age is approximately <strong>0.07</strong>. This reflects both the direct effect of age and any indirect effect through BMI (since older patients tend to have higher BMI in this simulated dataset).</p>
<p><strong>Part (b)</strong></p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(fit_multiple)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>(Intercept)         age         bmi 
 1.76416721  0.04353449  0.12194304 </code></pre>
</div>
</div>
<p>After including BMI, the slope for age is approximately <strong>0.05</strong> — closer to the true value. This is because the multiple regression <strong>adjusts for BMI</strong>, removing the confounding effect. BMI was partially absorbing the age effect in the simple model.</p>
<p><strong>Part (c)</strong> The BMI coefficient (~0.10) is interpreted as: holding age constant, each 1-unit increase in BMI is associated with a <strong>0.10 ng/mL increase</strong> in the biomarker concentration, on average.</p>
</div>
</div>
</div>
<hr>
<ol start="12" type="1">
<li>Using the NHANES dataset, a logistic regression models the probability of diabetes as a function of BMI and Age:</li>
</ol>
<p><span class="math display">\[\text{logit}(p) = -8.08 + 0.094 \times \text{BMI} + 0.057 \times \text{Age}\]</span></p>
<ol type="a">
<li><p>Compute the predicted probability of diabetes for a 55-year-old with BMI = 32.</p></li>
<li><p>Compute and interpret the odds ratio for BMI.</p></li>
<li><p>Is BMI or Age a stronger predictor in this model on the log-odds scale? How would you compare them more fairly?</p></li>
<li><p>A patient’s BMI increases from 28 to 38 (a 10-unit increase). By what factor do their odds of diabetes change?</p></li>
</ol>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-10-contents" aria-controls="callout-10" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Solution
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-10" class="callout-10-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>Part (a)</strong></p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a>b0 <span class="ot">&lt;-</span> <span class="sc">-</span><span class="fl">8.08</span>; b_bmi <span class="ot">&lt;-</span> <span class="fl">0.094</span>; b_age <span class="ot">&lt;-</span> <span class="fl">0.057</span></span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>linear <span class="ot">&lt;-</span> b0 <span class="sc">+</span> b_bmi <span class="sc">*</span> <span class="dv">32</span> <span class="sc">+</span> b_age <span class="sc">*</span> <span class="dv">55</span></span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a>p_hat  <span class="ot">&lt;-</span> <span class="fu">exp</span>(linear) <span class="sc">/</span> (<span class="dv">1</span> <span class="sc">+</span> <span class="fu">exp</span>(linear))</span>
<span id="cb32-4"><a href="#cb32-4" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(p_hat, <span class="dv">4</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.126</code></pre>
</div>
</div>
<p>The predicted probability is approximately <strong>14.6%</strong>.</p>
<p><strong>Part (b)</strong></p>
<p><span class="math display">\[OR_{\text{BMI}} = e^{0.094} \approx 1.099\]</span></p>
<p>Each 1-unit increase in BMI is associated with approximately <strong>9.9% higher odds</strong> of diabetes, holding age constant.</p>
<p><strong>Part (c)</strong> The raw coefficients (0.094 vs.&nbsp;0.057) are on different scales (BMI units vs.&nbsp;years), so they cannot be compared directly. To compare fairly, use <strong>standardized coefficients</strong> (multiply each <span class="math inline">\(\beta\)</span> by the standard deviation of that predictor) or compare <strong>odds ratios per standard deviation change</strong>.</p>
<p><strong>Part (d)</strong></p>
<p><span class="math display">\[OR = e^{0.094 \times 10} = e^{0.94} \approx 2.56\]</span></p>
<p>A 10-unit increase in BMI is associated with <strong>2.56 times higher odds</strong> of diabetes, holding age constant.</p>
</div>
</div>
</div>
<hr>
<ol start="13" type="1">
<li>A clinical trial follows 8 patients after treatment. Their survival times (months) and event status (1 = died, 0 = censored) are:</li>
</ol>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a>times  <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">3</span>, <span class="dv">5</span>, <span class="dv">6</span>, <span class="dv">6</span>, <span class="dv">8</span>, <span class="dv">10</span>, <span class="dv">12</span>, <span class="dv">15</span>)</span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>events <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">0</span>, <span class="dv">1</span>, <span class="dv">0</span>,  <span class="dv">1</span>,  <span class="dv">0</span>)</span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-4"><a href="#cb34-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(survival)</span>
<span id="cb34-5"><a href="#cb34-5" aria-hidden="true" tabindex="-1"></a>fit <span class="ot">&lt;-</span> <span class="fu">survfit</span>(<span class="fu">Surv</span>(times, events) <span class="sc">~</span> <span class="dv">1</span>)</span>
<span id="cb34-6"><a href="#cb34-6" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(fit,</span>
<span id="cb34-7"><a href="#cb34-7" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">"Time (months)"</span>,</span>
<span id="cb34-8"><a href="#cb34-8" aria-hidden="true" tabindex="-1"></a>     <span class="at">ylab =</span> <span class="st">"Survival probability"</span>,</span>
<span id="cb34-9"><a href="#cb34-9" aria-hidden="true" tabindex="-1"></a>     <span class="at">main =</span> <span class="st">"Kaplan-Meier Curve"</span>,</span>
<span id="cb34-10"><a href="#cb34-10" aria-hidden="true" tabindex="-1"></a>     <span class="at">lwd  =</span> <span class="dv">2</span>, <span class="at">col =</span> <span class="st">"steelblue"</span>,</span>
<span id="cb34-11"><a href="#cb34-11" aria-hidden="true" tabindex="-1"></a>     <span class="at">conf.int =</span> <span class="cn">TRUE</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="review_problems_soln_files/figure-html/unnamed-chunk-16-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<ol type="a">
<li><p>What is the estimated probability of surviving beyond 10 months?</p></li>
<li><p>One patient was censored at month 6. What does this mean, and how does the KM estimator handle it?</p></li>
</ol>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-11-contents" aria-controls="callout-11" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Solution
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-11" class="callout-11-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>Part (a)</strong></p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Time</th>
<th><span class="math inline">\(n_{\text{risk}}\)</span></th>
<th><span class="math inline">\(d_i\)</span></th>
<th><span class="math inline">\(1 - d_i/n_i\)</span></th>
<th><span class="math inline">\(\hat{S}(t)\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>3</td>
<td>8</td>
<td>1</td>
<td>7/8</td>
<td>0.875</td>
</tr>
<tr class="even">
<td>5</td>
<td>7</td>
<td>1</td>
<td>6/7</td>
<td>0.750</td>
</tr>
<tr class="odd">
<td>6</td>
<td>6</td>
<td>1</td>
<td>5/6</td>
<td>0.625</td>
</tr>
<tr class="even">
<td>8</td>
<td>4</td>
<td>1</td>
<td>3/4</td>
<td>0.469</td>
</tr>
<tr class="odd">
<td>12</td>
<td>2</td>
<td>1</td>
<td>1/2</td>
<td>0.234</td>
</tr>
</tbody>
</table>
<p>At <span class="math inline">\(t = 6\)</span>, one patient is censored (exits the risk set before the event at that time), so <span class="math inline">\(n_{\text{risk}} = 6\)</span>.</p>
<p><strong>Part (b)</strong></p>
<p><span class="math inline">\(\hat{S}(10) = \hat{S}(8) = 0.469\)</span> (no events between <span class="math inline">\(t = 8\)</span> and <span class="math inline">\(t = 10\)</span>; the next event is at <span class="math inline">\(t = 12\)</span>).</p>
<p>The estimated probability of surviving beyond 10 months is approximately <strong>46.9%</strong>.</p>
<p><strong>Part (c)</strong> Censoring at month 6 means the patient left follow-up at that point (e.g., withdrew, was lost to follow-up, or the study ended) without experiencing the event. The KM estimator handles censoring by removing the censored patient from the risk set at their censoring time, without treating them as having died. This uses all available information without biasing the estimate.</p>
<p><strong>Part (d)</strong></p>
<p>The step-down curve shows survival probability decreasing at each event time. Tick marks on the curve indicate censored observations.</p>
</div>
</div>
</div>
<p>Formulas: unpooled SE: <span class="math display">\[
\mathrm{SE}\!\left(\bar X_1-\bar X_2\right)
= \sqrt{\frac{s_1^{2}}{n_1}+\frac{s_2^{2}}{n_2}}
\]</span></p>
<p>degrees of freedom: <span class="math display">\[
\mathrm{df}
=
\frac{\left(\frac{s_T^2}{n_T}+\frac{s_C^2}{n_C}\right)^2}
{\frac{\left(\frac{s_T^2}{n_T}\right)^2}{n_T-1}
+
\frac{\left(\frac{s_C^2}{n_C}\right)^2}{n_C-1}}.
\]</span></p>
<p>Goodness of fit test</p>
<p><span class="math display">\[
\chi^{2}=\sum_{i}\frac{(\text{Observed}_{i}-\text{Expected}_{i})^2}{\text{Expected}_{i}}
\]</span></p>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>