# Activity 10 {#sec-week2}

Name:

1.  The following table shows the number of bacteria colonies present in each of several petri dishes, after E. coli bacteria were added to the dishes and they were incubated for 24 hours. The “soap” dishes contained a solution prepared from ordinary soap; the “control” dishes contained a solution of sterile water. Data for the control group is: 30, 36, 66 and for the soap group: 76, 27, 16. There are 20 possible randomizations of the six observations into two groups, each of size three.

    a) Create a list of these 20 randomizations (one of which is the original assignment of observations to the two groups) and for each case calculate the control mean minus the soap mean. How many of the 20 randomizations produce a difference in means at least as large as 4.3?

    b) Is there evidence that the soap inhibits E. coli growth? Justify your answer using the randomization results.


2. Suppose we have conducted a test, with $\alpha = 0.10$,
and the p-value is 0.07. For each of the following statements, say whether the statement is true or false and explain why.
(a) We reject with $H_0$ with $\alpha=0.10$
(b) We have significant evidence for $H_{A}$ with $\alpha=0.1$
(c) We would reject $H_{0}$ if were 0.05.
(d) We do not have significant evidence for $H_{A}$ with $\alpha=0.05$
(e) The probability that $\bar{Y}_{1}$ is greater than $\bar{Y}_{2}$ is 0.07.

