# Activity 15 {#sec-week2}

Name:


1.  Find the confidence interval for $\rho$ in the cats example.



2. The Pioneer Valley Planning Commission (PVPC) collected data north of Chestnut Street in Florence, Massachusetts for a 90-day period. Data collectors set up a laser sensor that recorded when a rail-trail user passed the data collection station. The data area available in the $\texttt{RailTrail}$ data set in the $\textbf{mosaicData}$ package.

(a) The PVPC wants to understand the relationship between daily ridership (volume) and temperature (hightemp). Display the scatterplot and visually assess the linear relationship.

(b) Fit a linear regression and estimate the coefficients. What is the interpretation of the value of the coefficients?

(c) Add the line to the scatterplot. 


(d) How does your model compare to a null model? That is, how much of the variation in daily ridership is explained by the regression model based on average daily temperature?



(e) What is the confidence interval of $\beta_{1}$ and what is the interpretation.

