# Activity 13 {#sec-week2}

Name:



1. In a study in Scotland, researchers left a total of 240 wallets around Edinburgh, as though the wallets were lost. Each contained contact information including an address. Of the wallets, 101 were returned by the people who found them. With the following steps, use the data to estimate the proportion of lost wallets that are returned, and give a 95% confidence interval for this estimate.

(a) What is the observed proportion of wallets that were returned?


(b) Calculate $p^'$ to use in the Agresti-Coull method of calculating a 95% confidence interval for the population proportion.

(c) Calculate the 95% confidence interval

(d) What is the interpretation of your confidence interval?

(e) If the authros had tested the null hypothesis that $p$ was $1/2$ at a signficance level $0.05$, it it likely that they would have rejected the null hypothesis?

2. The drug ancrod was tested in a double-blind
clinical trial in which subjects who had strokes were 
randomly assigned to get either ancrod or a placebo. One
response variable in the study was whether or not a
subject experienced intracranial hemorrhaging. The
data are provided in the following table. Use a chi-square
test to determine whether the difference in hemorrhaging 
rates is statistically significant. Use a nondirectional alternative
and let $\alpha=0.05$

```{r}
#| warning: false

# Contingency table: rows = (Yes, No), cols = (Ancrod, Placebo)
tab <- matrix(
  c(13, 235,
    5, 247),
  nrow = 2, byrow = FALSE,
  dimnames = list(
    Hemorrage = c("Yes", "No"),
    Treatment   = c("Ancrod", "Placebo")
  )
)

#tab
addmargins(tab)  # show row/column totals

```

(a) State the null and alternative hypotheses


